### ISSUE TITLE
Use ISO 8601 date format for villagers birthday

### ISSUE THREAD

**Issue by n8felton** [alexislours/ACNHAPI#9]
To help avoid confusion with date formats, I recommend either switching the `birthday` field to using the ISO 8601 date format `YYYY-MM-DD`, or creating a new field like `birthday-iso8601`

While I don't believe birthday year is part of the data, perhaps it would a fun side project to determine birth year based on the release date of the game the villager first appears in. In the absence of a birthday year, you can use `XXXX`

For example, Annalisa's birthday would be `XXXX-02-06` to help recognize that it's `February 6th`, not `June 2nd` (without needing to parse the `birthday-string` field).

Looking at https://animalcrossing.fandom.com/wiki/Annalisa, it appears Annalisa was a new character in New Leaf, which has an original release date of November 8th, 2012 (in Japan), which would make her birth year `2012`, and her full birthday `2012-02-06`.

**Comment by alexislours** [comment]
Specified the date format in the doc (day/month). Bringing an ISO for the sake of bringing an ISO would just bring more confusion than anything else.

These data are extracted directly from the game (which also uses the day/month for internally) and having a year would "corrupt" the data. 

Also, making the date XXXX-02-06 would go against ISO 8601 as omitting years is against the standard.

**Comment by igromanru** [comment]
Just want to add my two cents.  
Beside what @alexislours said, that the year is not given by Nintendo and we should use the data how it was dumped from the game, it's a very bad idea to try add an birth year on our own.  
Because this information would be wrong and misleading, animals are definitely much older than their release date, you can feel it from conversations with them.  

The only thing that I would add, if it given by the game, is the translation for each region like for names. The same applies to catch-phrase and personality. I know that at least the catch phrase is different depends on the language.

**Comment by alexislours** [comment]
I'll add an object containing the catch-phrase translations. The personality doesn't really have an "official translation" so it would have to be mapped for each language by the user. The game use two letter codes such as "AN" for Uchi/Sisterly.
